# Numpy Crash Course

https://www.youtube.com/watch?v=lLRBYKwP8GQ  
https://www.youtube.com/watch?v=E1IPJOd7dWQ

## 1. Create

### 1.1. Arrays with `.arange()` method

In [2]:
import numpy as np

In [5]:
my_arr = np.arange(8) # (stop)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
my_arr = np.arange(1, 8) # (start, stop)
my_arr

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
my_arr = np.arange(1, 8, 2) # (start, stop, step)
my_arr

array([1, 3, 5, 7])

In [10]:
my_arr = np.arange(-1, 8, 0.5) # (start, stop, step)
my_arr

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,
        4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5])

### 1.2. Arrays from Lists

In [12]:
from_list = np.array([1, 2, 3])
from_list

array([1, 2, 3])

In [14]:
type(from_list[0])

numpy.int64

Here we don't need 64 bits because our largest number in the list is 3, which only takes 2 bits (3 = 11 in binary). Therefore:

In [15]:
from_list = np.array([1, 2, 3], dtype=np.int8)
type(from_list[0])

numpy.int8

### 1.3. 2D Arrays

In [16]:
from_list = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int8)
from_list

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [18]:
my_arr = np.array((np.arange(0, 8, 2), np.arange(1, 8, 2)))
my_arr

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [20]:
my_arr.shape # output: (rows, columns)

(2, 4)

In [21]:
## Reshaping an 2d array:
my_arr = my_arr.reshape((4, 2))
my_arr

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [22]:
my_arr = my_arr.reshape(8)
my_arr

array([0, 2, 4, 6, 1, 3, 5, 7])

In [23]:
my_arr = my_arr.reshape((2, 2, 2))
my_arr

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

### 1.4. Empty Arrays

In [24]:
empty_arr = np.zeros((2, 2))
empty_arr

array([[0., 0.],
       [0., 0.]])

In [26]:
empty_arr = np.ones((2, 2))
empty_arr

array([[1., 1.],
       [1., 1.]])

In [27]:
# empty_arr = np.empty((2, 2)) returns random numbers. not recommended

In [28]:
eye_arr = np.eye(3) # 3x3 where main diagonal is filled with 1s, the rest with 0s
print(eye_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
eye_arr = np.eye(3, k=-1) # 3x3 where one diagonel below the main diagonal is filled with 1s, the rest with 0s
print(eye_arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


### Replacing values in an array

In [31]:
eye_arr = np.eye(3, k=1) # 3x3 where one diagonel above the main diagonal is filled with 1s, the rest with 0s
eye_arr[eye_arr == 0] = 2 # replacing 0s with 2s
print(eye_arr)

[[2. 1. 2.]
 [2. 2. 1.]
 [2. 2. 2.]]


In [32]:
eye_arr[0] = 3 # changing the values of the entire first row
eye_arr

array([[3., 3., 3.],
       [2., 2., 1.],
       [2., 2., 2.]])

In [34]:
# Changing an entire column
eye_arr[:, 0] = 8 # remember the slicing of the lists, same logic here
eye_arr

array([[8., 3., 3.],
       [8., 2., 1.],
       [8., 2., 2.]])

### Sorting arrays

In [40]:
sorted_arr = np.sort(eye_arr)
print("Original arr:\n", eye_arr, "\nSorted arr:\n", sorted_arr)

Original arr:
 [[8. 3. 3.]
 [8. 2. 1.]
 [8. 2. 2.]] 
Sorted arr:
 [[3. 3. 8.]
 [1. 2. 8.]
 [2. 2. 8.]]


In [41]:
col_sorted_arr = np.sort(eye_arr, axis=0) # 0 for colums, -1 for rows (default)
print("Original arr:\n", eye_arr, "\nSorted by columns arr:\n", col_sorted_arr)

Original arr:
 [[8. 3. 3.]
 [8. 2. 1.]
 [8. 2. 2.]] 
Sorted by columns arr:
 [[8. 2. 1.]
 [8. 2. 2.]
 [8. 3. 3.]]


### Copying Arrays

In [42]:
# .view() method creates a view, not a copy! If we modify the values view, we also modify the original array. (This doesn't apply to the shape though, reshaping a view doesn't reshape the original)
my_view = sorted_arr.view() 

# .copy() method created a copy
my_copy = sorted_arr.copy()

## Operations